import openai
from utils.text_utils import split_text_into_chunks

def summarize_with_openai(text, abstract_length):
    """
    Summarizes a large text using OpenAI's API with strict 
    length and sentence control.
    """
    try:
        print("Starting summarization process...")
        max_sentences_summary = min(3, abstract_length)  # Maximum of 3 sentences
        chunks = split_text_into_chunks(text)
        summary_parts = []
        
        for chunk in chunks:
            max_completion_tokens = max(50, int(abstract_length * 0.2))
            response = openai.chat.completions.create(
                model="gpt-4",
                messages=[
                    {
                        "role": "system",
                        "content": ("You are a highly skilled assistant that summarizes academic and technical "
                                    "content concisely and accurately.")
                    },
                    {
                        "role": "user",
                        "content": (
                            f"Summarize the following text in {max_sentences_summary} sentences or fewer. "
                            "Focus on the main ideas, key concepts, and conclusions. Ensure the summary is clear, "
                            "concise, and free of irrelevant details. Here is the text:\n" + chunk
                        )
                    }
                ],
                max_tokens=max_completion_tokens,
                temperature=0.2,
                stop=["\n"]
            )
            
            if not response.choices or len(response.choices) == 0:
                raise ValueError("No summary generated by OpenAI.")
            
            summary = response.choices[0].message.content.strip()
            if not summary.endswith('.'):
                summary += '.'
            summary_parts.append(summary)
        
        final_summary = " ".join(summary_parts)
        summary_words = final_summary.split()
        if len(summary_words) > abstract_length:
            truncated_summary = []
            word_count = 0
            for sentence in final_summary.split('. '):
                sentence_words = sentence.split()
                if word_count + len(sentence_words) <= abstract_length:
                    truncated_summary.append(sentence)
                    word_count += len(sentence_words)
                else:
                    break
            final_summary = ". ".join(truncated_summary) + "."
        
        print(f"Summary generated successfully. Length: {len(final_summary)} characters.")
        return final_summary

    except Exception as e:
        print(f"Unexpected error in summarize_with_openai: {str(e)}")
        return "Failed to generate summary."
